### ISSUE TITLE
设置子菜单为dropdown样式

### ISSUE THREAD

**Issue by alvin86** [LoeiFy/Diaspora#17]
LoeiFy大大，您好：
我非常喜欢您的Diaspora主题，并感谢您共享主题代码。
作为一个菜鸟，现在使用这个主题过程中遇到两个问题，麻烦予以解答：
一个是如何把菜单改成dropdown样式？
另一个是顶部logo图片如果比较长应该如何添加？我尝试修改了一下css，图片还是会被强制缩放。
谢谢

**Comment by LoeiFy** [comment]
@alvin86 
1）关于下拉菜单，由于菜单是整个页面展开的，所以没有计划做下拉菜单，也没有想好怎么弄
2）在 Diaspora.css 66 － 77

``` css
.image-logo {
    z-index: 4;
    position: relative;
    display: inline-block;

    /* 这里设置成你 logo 宽高 1/2 */
    -webkit-background-size: 62px 26px;
    -moz-background-size: 62px 26px;
    background-size: 62px 26px;

    background-repeat: no-repeat;
    background-position: center center;

    /* 这里设置成你 logo 宽高 1/2 */
    width: 62px;
    height: 26px;
}
```
