### ISSUE TITLE
音乐自动播放是否自动播放和循环

### ISSUE THREAD

**Issue by linmi** [LoeiFy/Diaspora#5]
建议使用audio标签  [audio  autoplay="auto" loop="ture" src="http://m1.music.126.net/Q2wx7EaeuS_bnqlEJ85u0Q==/2881819977150355.mp3"]

参考：https://codex.wordpress.org/Audio_Shortcode

**Comment by LoeiFy** [comment]
这个觉得可以添加。

之前没有做这个功能是因为，对于 guo.lu 文章内容作者来说，他喜欢直接在 wordpress 后台上传音乐文件，然后插入到文章中，因为一直以来都是这样，已经很多这样的文章了，改格式很麻烦，所以就一直沿用插入方式

**Comment by linmi** [comment]
哈哈，我继续看看

**Comment by yxling** [comment]
看你guo.lu文章里面的音乐播放器看不见，在编辑器写文章的时候添加音乐后也没找到把音乐播放器设置为不可见的选项，你是怎么弄的。

**Comment by LoeiFy** [comment]
@yxling audio 被我隐藏了

``` css
audio {
    display: none;
    visibility: hidden;
    opacity: 0;
    width: 0;
    height: 0;
}
```
